"""K9-v3 不可变成绩包。

这里是唯一的 v3 成绩写入口。D0 候选只能创建一次，D1/D2 只允许向前追加；所有
读取路径使用 ``readonly_tables``，绝不借读取触发 schema 初始化。
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import date, datetime, time
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional, Sequence

from neckline.db import connection, readonly_tables
from neckline.calendar import CN_TZ

STRATEGY_VERSION = "K9-v3"
FACT_PACK_VERSION = "fp-4"
LABEL_CONTRACT_VERSION = "d2-v2"


class PackageConflict(RuntimeError):
    pass


@dataclass(frozen=True)
class Candidate:
    ts_code: str
    name: Optional[str]
    sw_l2_code: Optional[str]
    sw_l2_name: Optional[str]
    channels: Sequence[str]
    channel_ranks: Mapping[str, int]
    playbook: Mapping[str, Any]
    baseline: Mapping[str, Any]
    thresholds: Mapping[str, Any]


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")


def _d(value: date) -> str:
    return value.strftime("%Y%m%d")


def _json(value: Mapping[str, Any] | Sequence[Any]) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def create_batch(*, batch_id: str, selection_date: date, signal_trade_date: date,
                 d1_trade_date: date, d2_trade_date: date, revision: int,
                 params_package_version: str, params_sha256: str, pack_id: str,
                 frozen_contract: Mapping[str, Any], candidates: Iterable[Candidate],
                 playbook_provenance: Optional[Mapping[str, Any]] = None,
                 db_path: Optional[Path] = None) -> None:
    """原子写入一个 D0 包；同一身份重跑只接受完全相同的数据。"""
    rows = tuple(candidates)
    now = _now()
    with connection(db_path) as conn:
        existing = conn.execute(
            "SELECT frozen_contract_json FROM k9_selection_batches WHERE batch_id=?", (batch_id,)
        ).fetchone()
        frozen = _json(frozen_contract)
        if existing is not None:
            if existing[0] != frozen:
                raise PackageConflict(f"batch {batch_id} 已存在且冻结合同不同")
            return
        initial_state = "settled" if not rows else "d0"
        coverage_state = "complete" if not rows else "pending"
        conn.execute(
            """INSERT INTO k9_selection_batches
            (batch_id,selection_date,signal_trade_date,d1_trade_date,d2_trade_date,revision,state,
             coverage_state,strategy_version,params_package_version,params_sha256,pack_id,pack_version,
             label_contract_version,frozen_contract_json,created_at)
            VALUES (?,?,?,?,?,?, ?, ?,?,?,?,?,?,?,?,?)""",
            (batch_id, _d(selection_date), _d(signal_trade_date), _d(d1_trade_date), _d(d2_trade_date),
             revision, initial_state, coverage_state, STRATEGY_VERSION, params_package_version, params_sha256, pack_id,
             FACT_PACK_VERSION, LABEL_CONTRACT_VERSION, frozen, now),
        )
        conn.executemany(
            """INSERT INTO k9_selection_candidates
            (batch_id,ts_code,name,sw_l2_code,sw_l2_name,channels_json,channel_ranks_json,
             frozen_playbook_json,baseline_json,thresholds_json,created_at)
            VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
            [(batch_id, c.ts_code, c.name, c.sw_l2_code, c.sw_l2_name,
              _json(sorted(c.channels)), _json(dict(c.channel_ranks)), _json(dict(c.playbook)),
              _json(dict(c.baseline)), _json(dict(c.thresholds)), now) for c in rows],
        )
        # Revision 1 is generated by the routed LLM and is atomically created
        # with D0.  Candidate frozen_playbook_json is never overwritten.
        conn.executemany(
            """INSERT INTO k9_playbook_revisions
            (batch_id,ts_code,revision,source,mechanical_json,provenance_json,created_at,confirmed_at,frozen_at)
            VALUES (?,?,?,?,?,?,?,?,?)""",
            [(batch_id, c.ts_code, 1, "llm", _json(dict(c.playbook)),
              _json(dict(playbook_provenance or {"source": "llm"})), now, now, None)
             for c in rows],
        )


def _latest_playbook(conn, batch_id: str, ts_code: str) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    rows = conn.execute(
        "SELECT revision,source,mechanical_json,provenance_json,created_at,confirmed_at,frozen_at "
        "FROM k9_playbook_revisions WHERE batch_id=? AND ts_code=? ORDER BY revision",
        (batch_id, ts_code),
    ).fetchall()
    history = [{"revision": r[0], "source": r[1], "playbook": json.loads(r[2]),
                "provenance": json.loads(r[3]), "createdAt": r[4], "confirmedAt": r[5], "frozenAt": r[6]}
               for r in rows]
    if not history:
        raise PackageConflict(f"{batch_id}/{ts_code} 缺少预案修订")
    current = dict(history[-1]["playbook"])
    current["revision"] = history[-1]["revision"]
    current["source"] = history[-1]["source"]
    return current, history


def _local_now(now: Optional[datetime] = None) -> datetime:
    value = now or datetime.now(CN_TZ)
    return value.replace(tzinfo=CN_TZ) if value.tzinfo is None else value.astimezone(CN_TZ)


def append_user_playbook_revision(*, batch_id: str, ts_code: str, playbook: Mapping[str, Any],
                                  provenance: Mapping[str, Any], db_path: Optional[Path] = None,
                                  now: Optional[datetime] = None) -> int:
    """Append a validated user revision before D1; never overwrite D0 or D1."""
    with connection(db_path) as conn:
        candidate = conn.execute(
            "SELECT channels_json,channel_ranks_json,baseline_json,thresholds_json FROM k9_selection_candidates "
            "WHERE batch_id=? AND ts_code=?", (batch_id, ts_code),
        ).fetchone()
        if candidate is None:
            raise PackageConflict("候选不存在")
        frozen = conn.execute("SELECT 1 FROM k9_playbook_freezes WHERE batch_id=? AND ts_code=?", (batch_id, ts_code)).fetchone()
        frozen = frozen or conn.execute("SELECT 1 FROM k9_package_checklists WHERE batch_id=?", (batch_id,)).fetchone()
        if frozen is not None:
            raise PackageConflict("D1 9:26 已冻结，本批预案不能再修改")
        d1 = conn.execute("SELECT d1_trade_date FROM k9_selection_batches WHERE batch_id=?", (batch_id,)).fetchone()
        clock = _local_now(now)
        # This is an absolute Shanghai cutoff, not a marker-dependent or
        # same-day-only guard.  A missed checklist service must never reopen
        # D1 revisions later that day (or on any later date).
        if d1 is not None:
            try:
                cutoff_day = datetime.strptime(str(d1[0]), "%Y%m%d").date()
            except ValueError as exc:
                raise PackageConflict("成绩包 D1 日期无效，拒绝修改预案") from exc
            cutoff = datetime.combine(cutoff_day, time(9, 26), tzinfo=CN_TZ)
            if clock >= cutoff:
                raise PackageConflict("D1 09:26（上海时间）已到，预案不能再修改")
        maximum = conn.execute("SELECT COALESCE(MAX(revision),0) FROM k9_playbook_revisions WHERE batch_id=? AND ts_code=?", (batch_id, ts_code)).fetchone()[0]
        revision = int(maximum) + 1
        payload = dict(playbook); payload["revision"] = revision; payload["source"] = "user"
        conn.execute(
            "INSERT INTO k9_playbook_revisions(batch_id,ts_code,revision,source,mechanical_json,provenance_json,created_at,confirmed_at,frozen_at) "
            "VALUES (?,?,?,?,?,?,?,?,?)",
            (batch_id, ts_code, revision, "user", _json(payload), _json(dict(provenance)), _now(), _now(), None),
        )
    return revision


def freeze_playbook_revision(*, batch_id: str, ts_code: str, db_path: Optional[Path] = None) -> tuple[int, dict[str, Any]]:
    """Return and mark the last revision used by D1's immutable checklist."""
    with connection(db_path) as conn:
        current, _history = _latest_playbook(conn, batch_id, ts_code)
        revision = int(current["revision"])
        conn.execute("UPDATE k9_playbook_revisions SET frozen_at=COALESCE(frozen_at,?) WHERE batch_id=? AND ts_code=? AND revision=?",
                     (_now(), batch_id, ts_code, revision))
    return revision, current


def freeze_checklist_atomic(package: Mapping[str, Any], *, trade_date: date,
                            readings: Mapping[str, Mapping[str, Any]],
                            now: Optional[datetime] = None,
                            db_path: Optional[Path] = None) -> Any:
    """Freeze all D1 revisions and its checklist in one SQLite transaction."""
    from neckline.auction import checklist
    clock = _local_now(now)
    if clock.date() != trade_date or clock.timetz().replace(tzinfo=None) < time(9, 26):
        raise PackageConflict("D1 核对只能在 09:26 后冻结")
    batch_id = str(package["batch_id"])
    with connection(db_path) as conn:
        existing = conn.execute("SELECT checklist_json FROM k9_package_checklists WHERE batch_id=?", (batch_id,)).fetchone()
        if existing is not None:
            # Idempotent replays must retain the actual segment rows.  A crash
            # after checklist commit but before dedup/push needs to reconstruct
            # the true counts rather than emitting an empty 0/0 payload.
            from types import SimpleNamespace
            stored = json.loads(existing[0])
            rows = tuple(
                SimpleNamespace(verdict=str(row["verdict"]))
                for segment in stored.get("segments", []) if isinstance(segment, dict)
                for row in segment.get("rows", []) if isinstance(row, dict)
                and row.get("verdict") in {"rejected", "unbuyable", "pending_open"}
            )
            return SimpleNamespace(as_dict=lambda: stored, rows=rows)
        mutable = {**package, "candidates": []}
        for original in package["candidates"]:
            code = str(original["tsCode"])
            prior = conn.execute("SELECT revision,mechanical_json FROM k9_playbook_revisions WHERE batch_id=? AND ts_code=? ORDER BY revision DESC LIMIT 1", (batch_id, code)).fetchone()
            if prior is None:
                raise PackageConflict(f"{batch_id}/{code} 缺少预案修订")
            revision, serialized = int(prior[0]), str(prior[1])
            plan = json.loads(serialized); plan["revision"] = revision
            digest = hashlib.sha256(serialized.encode("utf-8")).hexdigest()
            old = conn.execute("SELECT revision,playbook_sha256 FROM k9_playbook_freezes WHERE batch_id=? AND ts_code=?", (batch_id, code)).fetchone()
            if old is not None and (int(old[0]) != revision or str(old[1]) != digest):
                raise PackageConflict(f"{batch_id}/{code} 的 D1 冻结身份冲突")
            conn.execute("INSERT OR IGNORE INTO k9_playbook_freezes(batch_id,ts_code,revision,frozen_at,reason,playbook_sha256) VALUES (?,?,?,?,?,?)",
                         (batch_id, code, revision, clock.isoformat(timespec="seconds"), "d1_0926", digest))
            item = dict(original); item["playbook"] = plan; mutable["candidates"].append(item)
        snapshot = checklist.build_checklist(mutable, trade_date=trade_date, readings=readings)
        payload = json.dumps(snapshot.as_dict(), ensure_ascii=False, sort_keys=True)
        conn.execute("INSERT INTO k9_package_checklists(batch_id,trade_date,checklist_json,created_at) VALUES(?,?,?,?)",
                     (batch_id, trade_date.strftime("%Y%m%d"), payload, clock.isoformat(timespec="seconds")))
    return snapshot


def append_d1(*, batch_id: str, ts_code: str, checklist_verdict: str,
              open_verdict: Optional[str], reference_price: Optional[float],
              raw: Mapping[str, Any], close_state: Optional[str] = None,
              db_path: Optional[Path] = None) -> None:
    """追加 10:00 分支；D1 收盘评价必须走 :func:`append_d1_close`。

    这两个时点不能共用一条可更新记录，否则收盘处理会改写已冻结的 10:00
    判定。``reference_price`` 仅在可交易的成立/观察状态才可以有值。
    """
    if checklist_verdict not in {"rejected", "unbuyable", "pending_open"}:
        raise ValueError("未知 9:29 核对结论")
    if open_verdict not in {"confirmed", "rejected", "observed", "unbuyable", "unavailable"}:
        raise ValueError("未知 10:00 结论")
    if open_verdict in {"rejected", "unbuyable", "unavailable"} and reference_price is not None:
        raise ValueError("不可交易分支不能带 D1 10:00 参考价")
    if open_verdict in {"confirmed", "observed"} and (reference_price is None or float(reference_price) <= 0):
        raise ValueError("可交易分支必须有有效 D1 10:00 参考价")
    payload = _json(raw)
    with connection(db_path) as conn:
        old = conn.execute("SELECT checklist_verdict,open_verdict,reference_price,raw_json FROM k9_selection_d1 WHERE batch_id=? AND ts_code=?",
                           (batch_id, ts_code)).fetchone()
        if old is not None:
            expected = (checklist_verdict, open_verdict, reference_price, payload)
            if old != expected:
                raise PackageConflict(f"{batch_id}/{ts_code} 的 D1 已冻结")
        else:
            conn.execute(
                """INSERT INTO k9_selection_d1
                (batch_id,ts_code,checklist_verdict,open_verdict,reference_price,close_state,raw_json,captured_at)
                VALUES (?,?,?,?,?,NULL,?,?)""",
                (batch_id, ts_code, checklist_verdict, open_verdict, reference_price, payload, _now()),
            )
            conn.execute("UPDATE k9_selection_batches SET state='d1' WHERE batch_id=? AND state='d0'", (batch_id,))
    # Compatibility only for an already captured D1-close replay: it still
    # writes the separate append-only table, never the 10:00 record.
    if close_state is not None:
        append_d1_close(batch_id=batch_id, ts_code=ts_code, close_state=close_state,
                        raw=raw, db_path=db_path)


def append_d1_close(*, batch_id: str, ts_code: str, close_state: str,
                    raw: Mapping[str, Any], db_path: Optional[Path] = None) -> None:
    """追加 D1 收盘状态及原始值，永不覆盖 10:00 分支。"""
    if close_state not in {"enhanced", "held", "weakened", "unavailable"}:
        raise ValueError("未知 D1 收盘状态")
    payload = _json(raw)
    with connection(db_path) as conn:
        old = conn.execute(
            "SELECT close_state,raw_json FROM k9_selection_d1_close WHERE batch_id=? AND ts_code=?",
            (batch_id, ts_code),
        ).fetchone()
        if old is not None:
            if old != (close_state, payload):
                raise PackageConflict(f"{batch_id}/{ts_code} 的 D1 收盘已冻结")
            return
        conn.execute(
            "INSERT INTO k9_selection_d1_close(batch_id,ts_code,close_state,raw_json,captured_at) VALUES (?,?,?,?,?)",
            (batch_id, ts_code, close_state, payload, _now()),
        )


def append_d2(*, batch_id: str, ts_code: str, selection_result: str,
              playbook_result: Optional[str], risk_tag: Optional[str], raw: Mapping[str, Any],
              db_path: Optional[Path] = None) -> None:
    payload = _json(raw)
    with connection(db_path) as conn:
        old = conn.execute("SELECT selection_result,playbook_result,risk_tag,raw_json FROM k9_selection_d2 WHERE batch_id=? AND ts_code=?",
                           (batch_id, ts_code)).fetchone()
        if old is not None:
            if old != (selection_result, playbook_result, risk_tag, payload):
                raise PackageConflict(f"{batch_id}/{ts_code} 的 D2 已冻结")
            return
        conn.execute(
            """INSERT INTO k9_selection_d2
            (batch_id,ts_code,selection_result,playbook_result,risk_tag,raw_json,settled_at)
            VALUES (?,?,?,?,?,?,?)""",
            (batch_id, ts_code, selection_result, playbook_result, risk_tag, payload, _now()),
        )
        totals = conn.execute("SELECT COUNT(*) FROM k9_selection_candidates WHERE batch_id=?", (batch_id,)).fetchone()[0]
        settled = conn.execute("SELECT COUNT(*) FROM k9_selection_d2 WHERE batch_id=?", (batch_id,)).fetchone()[0]
        if totals == settled:
            unavailable = conn.execute(
                "SELECT COUNT(*) FROM k9_selection_d2 WHERE batch_id=? AND selection_result='unavailable'", (batch_id,)
            ).fetchone()[0]
            coverage = "unavailable" if unavailable == totals else ("partial" if unavailable else "complete")
            conn.execute("UPDATE k9_selection_batches SET state='settled', coverage_state=? WHERE batch_id=?", (coverage, batch_id))


_BATCH_COLUMNS = ("batch_id,selection_date,signal_trade_date,d1_trade_date,d2_trade_date,revision,state,"
                  "coverage_state,strategy_version,params_package_version,params_sha256,pack_id,pack_version,"
                  "label_contract_version,created_at")
_PROBE = tuple(f"k9_selection_batches.{x}" for x in _BATCH_COLUMNS.split(","))


def load_selection_run(selection_date: date, *, db_path: Optional[Path] = None) -> Optional[dict[str, Any]]:
    """Read the durable D0 identity without causing a schema write."""
    with readonly_tables("k9_d0_run_markers.selection_date", db_path=db_path) as conn:
        if conn is None:
            return None
        row = conn.execute(
            "SELECT selection_date,signal_trade_date,state,batch_id,reason,created_at "
            "FROM k9_d0_run_markers WHERE selection_date=?", (_d(selection_date),)
        ).fetchone()
    if row is None:
        return None
    return dict(zip(("selection_date", "signal_trade_date", "state", "batch_id", "reason", "created_at"), row))


def record_selection_run(*, selection_date: date, signal_trade_date: date, state: str,
                         batch_id: Optional[str] = None, reason: Optional[str] = None,
                         db_path: Optional[Path] = None) -> None:
    """Persist the D0 result once; an idempotent replay must be byte-identical."""
    if state not in {"has_list", "empty", "not_run", "failed"}:
        raise ValueError("未知 D0 运行状态")
    with connection(db_path) as conn:
        old = conn.execute(
            "SELECT signal_trade_date,state,batch_id,reason FROM k9_d0_run_markers WHERE selection_date=?",
            (_d(selection_date),),
        ).fetchone()
        expected = (_d(signal_trade_date), state, batch_id, reason)
        if old is not None:
            if old == expected:
                return
            # Before a package exists, a missing parameter/fact can be repaired
            # and retried on the same public selection date.  Once a successful
            # immutable package is frozen its result identity cannot change.
            if old[1] in {"not_run", "failed"}:
                conn.execute(
                    "UPDATE k9_d0_run_markers SET signal_trade_date=?,state=?,batch_id=?,reason=?,created_at=? "
                    "WHERE selection_date=?",
                    (*expected, _now(), _d(selection_date)),
                )
                return
            raise PackageConflict(f"{_d(selection_date)} 的 D0 运行身份已冻结")
        conn.execute(
            "INSERT INTO k9_d0_run_markers(selection_date,signal_trade_date,state,batch_id,reason,created_at) "
            "VALUES (?,?,?,?,?,?)",
            (_d(selection_date), _d(signal_trade_date), state, batch_id, reason, _now()),
        )


def list_packages(*, state: str, db_path: Optional[Path] = None) -> list[dict[str, Any]]:
    if state not in {"active", "settled"}:
        raise ValueError("state 必须是 active 或 settled")
    clause = "state!='settled'" if state == "active" else "state='settled'"
    with readonly_tables(*_PROBE, "k9_selection_candidates.batch_id", db_path=db_path) as conn:
        if conn is None:
            return []
        rows = conn.execute(
            f"SELECT {_BATCH_COLUMNS},(SELECT COUNT(*) FROM k9_selection_candidates c WHERE c.batch_id=b.batch_id) "
            f"FROM k9_selection_batches b WHERE {clause} ORDER BY selection_date DESC,revision DESC"
        ).fetchall()
    keys = _BATCH_COLUMNS.split(",") + ["candidate_count"]
    return [dict(zip(keys, row)) for row in rows]


def load_package(batch_id: str, *, db_path: Optional[Path] = None) -> Optional[dict[str, Any]]:
    required = (*_PROBE, "k9_selection_candidates.batch_id", "k9_playbook_revisions.batch_id", "k9_playbook_freezes.batch_id", "k9_selection_d1.batch_id", "k9_selection_d1_close.batch_id", "k9_selection_d2.batch_id")
    with readonly_tables(*required, db_path=db_path) as conn:
        if conn is None:
            return None
        row = conn.execute(f"SELECT {_BATCH_COLUMNS},frozen_contract_json FROM k9_selection_batches WHERE batch_id=?", (batch_id,)).fetchone()
        if row is None:
            return None
        keys = _BATCH_COLUMNS.split(",") + ["frozen_contract"]
        result = dict(zip(keys, row))
        result["frozen_contract"] = json.loads(result["frozen_contract"])
        candidates = conn.execute(
            "SELECT ts_code,name,sw_l2_code,sw_l2_name,channels_json,channel_ranks_json,frozen_playbook_json,baseline_json,thresholds_json "
            "FROM k9_selection_candidates WHERE batch_id=? ORDER BY ts_code", (batch_id,)
        ).fetchall()
        revisions = {c[0]: _latest_playbook(conn, batch_id, c[0]) for c in candidates}
        frozen = {r[0]: r[1:] for r in conn.execute("SELECT ts_code,revision,playbook_sha256,frozen_at FROM k9_playbook_freezes WHERE batch_id=?", (batch_id,))}
        d1 = {r[0]: r[1:] for r in conn.execute("SELECT ts_code,checklist_verdict,open_verdict,reference_price,raw_json FROM k9_selection_d1 WHERE batch_id=?", (batch_id,))}
        d1_close = {r[0]: r[1:] for r in conn.execute("SELECT ts_code,close_state,raw_json FROM k9_selection_d1_close WHERE batch_id=?", (batch_id,))}
        d2 = {r[0]: r[1:] for r in conn.execute("SELECT ts_code,selection_result,playbook_result,risk_tag,raw_json FROM k9_selection_d2 WHERE batch_id=?", (batch_id,))}
    result["candidates"] = []
    for c in candidates:
        item = {"tsCode": c[0], "name": c[1], "swL2Code": c[2], "swL2Name": c[3],
                "channels": json.loads(c[4]), "channelRanks": json.loads(c[5]),
                "playbook": revisions[c[0]][0], "playbookHistory": revisions[c[0]][1],
                "frozenD0Playbook": json.loads(c[6]), "baseline": json.loads(c[7]), "thresholds": json.loads(c[8])}
        if c[0] in d1:
            x = d1[c[0]]; item["d1"] = {"checklistVerdict": x[0], "openVerdict": x[1], "referencePrice": x[2], "raw": json.loads(x[3])}
        if c[0] in d1_close:
            x = d1_close[c[0]]
            item.setdefault("d1", {})["closeState"] = x[0]
            item["d1"]["closeRaw"] = json.loads(x[1])
        if c[0] in frozen:
            x = frozen[c[0]]; item["d1Freeze"] = {"revision": x[0], "playbookSha256": x[1], "frozenAt": x[2]}
        if c[0] in d2:
            x = d2[c[0]]; item["d2"] = {"selectionResult": x[0], "playbookResult": x[1], "riskTag": x[2], "raw": json.loads(x[3])}
        result["candidates"].append(item)
    return result


def recent_locked_codes(*, before_selection_date: date, db_path: Optional[Path] = None) -> set[str]:
    """只按紧邻两个正式包锁定，不按自然日和结论放宽。"""
    with readonly_tables("k9_selection_batches.batch_id", "k9_selection_candidates.batch_id", db_path=db_path) as conn:
        if conn is None:
            return set()
        batches = conn.execute("SELECT batch_id FROM k9_selection_batches WHERE selection_date<? ORDER BY selection_date DESC,revision DESC LIMIT 2", (_d(before_selection_date),)).fetchall()
        return {r[0] for b in batches for r in conn.execute("SELECT ts_code FROM k9_selection_candidates WHERE batch_id=?", b)}


def aggregate_settled(*, db_path: Optional[Path] = None) -> dict[str, Any]:
    """只按完整版本谱系聚合 K9 可交易账；不产生综合分。

    D0 方向诊断和真实成交账故意不从本表读取，避免三条账相互污染。
    """
    required = (*_PROBE, "k9_selection_candidates.batch_id", "k9_selection_d1.batch_id", "k9_selection_d2.batch_id")
    with readonly_tables(*required, db_path=db_path) as conn:
        if conn is None:
            return {"groups": []}
        rows = conn.execute(
            "SELECT b.strategy_version,b.params_package_version,b.pack_version,b.label_contract_version,"
            "c.channels_json,d.selection_result,d.playbook_result,d.risk_tag "
            "FROM k9_selection_batches b JOIN k9_selection_candidates c ON c.batch_id=b.batch_id "
            "JOIN k9_selection_d2 d ON d.batch_id=c.batch_id AND d.ts_code=c.ts_code "
            "WHERE b.state='settled'"
        ).fetchall()
    groups: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    for strategy, params, pack, label, channels_json, result, playbook_result, risk_tag in rows:
        key = (strategy, params, pack, label)
        group = groups.setdefault(key, {"strategyVersion": strategy, "paramsPackageVersion": params,
                                        "packVersion": pack, "labelContractVersion": label,
                                        "selectionResults": {}, "playbookResults": {}, "riskTags": {},
                                        "channels": {"p2": 0, "p3": 0, "p4": 0}})
        group["selectionResults"][result] = group["selectionResults"].get(result, 0) + 1
        if playbook_result:
            group["playbookResults"][playbook_result] = group["playbookResults"].get(playbook_result, 0) + 1
        if risk_tag:
            group["riskTags"][risk_tag] = group["riskTags"].get(risk_tag, 0) + 1
        for channel in json.loads(channels_json):
            if channel in group["channels"]:
                group["channels"][channel] += 1
    return {"groups": list(groups.values())}


__all__ = ["Candidate", "PackageConflict", "create_batch", "append_user_playbook_revision", "freeze_playbook_revision", "freeze_checklist_atomic", "append_d1", "append_d1_close", "append_d2", "list_packages", "load_package", "load_selection_run", "record_selection_run", "recent_locked_codes", "aggregate_settled"]
